server:
  port: ${PORT:8088}

amazon:
  dynamodb:
    endpoint: ${AWS:http://192.168.8.106:30800}
  aws:
    accesskey: ${KEY:access}
    secretkey: ${SECRET:access}
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO